{ config, pkgs, ... }:

{
  services.paperless = {
    enable = true;
    address = "0.0.0.0";
    port = 28981;
    # Generated by `just install`. The previous approach wrote a hardcoded
    # "admin" into /etc/paperless-admin-pass, which was world-readable at 0444.
    passwordFile = "/var/lib/paperless/admin-pass";
    settings = {
      PAPERLESS_OCR_LANGUAGE = "deu+eng";
    };
    # PAPERLESS_TIME_ZONE defaults to config.time.timeZone.
  };
}
