{ config, pkgs, ... }:

let
  stateDir = "/var/lib/pihole";
in
{
  virtualisation.podman.enable = true;

  # Pi-hole owns port 53, so resolved's stub listener must stay out of the way.
  services.resolved.enable = false;

  # The host itself resolves against public DNS rather than through the
  # container: if Pi-hole is down, the box still has working name resolution
  # and `just update` can pull a fix.
  networking.nameservers = [
    "1.1.1.1"
    "8.8.8.8"
  ];

  systemd.tmpfiles.rules = [
    "d ${stateDir} 0755 1000 1000 -"
    "d ${stateDir}/etc-dnsmasq.d 0755 1000 1000 -"
  ];

  virtualisation.oci-containers.containers.pihole = {
    autoStart = true;
    image = "pihole/pihole:2025.11.1";

    # Pi-hole v6 removed the v5 variable names outright (WEBPASSWORD,
    # PIHOLE_DNS_, DNSMASQ_LISTENING, IPv6, REV_SERVER, CORS_HOSTS): they are
    # not read at all, so anything set under the old names silently does
    # nothing. Every setting below uses the FTLCONF_<section>_<key> form.
    # Note that settings passed as env vars become read-only in the web UI.
    environment = {
      TZ = config.time.timeZone;
      FTLCONF_dns_upstreams = "1.1.1.1;1.0.0.1";
      FTLCONF_dns_listeningMode = "all";
      FTLCONF_misc_etc_dnsmasq_d = "true";
    };

    # Supplies FTLCONF_webserver_api_password. Kept out of the store and out of
    # git; generated by `just install` (see `just set-pihole-pw` to rotate).
    environmentFiles = [ "${stateDir}/pihole.env" ];

    volumes = [
      "${stateDir}:/etc/pihole"
      "${stateDir}/etc-dnsmasq.d:/etc/dnsmasq.d"
    ];

    ports = [
      "53:53/tcp"
      "53:53/udp"
      "4000:80/tcp" # web UI, host:container
    ];

    extraOptions = [
      "--cap-add=NET_ADMIN"
      "--dns=1.1.1.1"
    ];
  };
}
