# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/e46cf0f8-6fb2-41dc-88cb-86ad4cbac084";
      fsType = "ext4";
    };

  fileSystems."/mnt/books" =
    { device = "systemd-1";
      fsType = "autofs";
    };

  fileSystems."/mnt/movies" =
    { device = "systemd-1";
      fsType = "autofs";
    };

  fileSystems."/mnt/music" =
    { device = "systemd-1";
      fsType = "autofs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/E142-12FF";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
